version: '3.4'

services:
  tss.api:
    image: ${DOCKER_REGISTRY-}tssapi
    build:
      context: .
      dockerfile: Tss.Api/Dockerfile
    env_file: .env
    # ports:
    #   - '8123:80'
    volumes:
      - ../data:/data
